// Builder's exclusive tool catalog. These tools are NOT globally
// registered — they have no entries in RegisteredChatTools(), can't
// be resolved by FindChatTool, and are invisible to every enumerator
// in the codebase. The Builder seed agent gets them by way of this
// constructor: when the runner assembles the catalog for an agent
// whose ID is "seed-builder", it appends the result of
// builderAuthoringTools() to the static tool list.
//
// Any other agent — Chat, Research, Phantom-dispatched agents, even
// a user-cloned Builder copy with a different ID — has no path to
// these tools. There's nothing to "filter out" because the tools
// were never in the pool to begin with.
//
// Ownership model: Builder ORCHESTRATOR is the assembler. It holds
// the full authoring catalog (create_agent / tool_def / etc.) and
// makes the create calls itself after reading worker drafts. Workers
// spawned via plan_set are research/drafting specialists: they probe
// APIs, draft scripts, run smoke tests, and report COMPONENTS back to
// Builder. Workers do NOT call create_agent / tool_def themselves —
// that's the orchestrator's job. This split fixes the prior failure
// mode where one worker tried to BOTH draft a script AND wrap it
// into a tool in a single fresh context, with no way for Builder to
// catch filename / param / template drift before commit.

package orchestrate

import (
	"fmt"
	"strings"

	. "github.com/cmcoffee/gohort/core"
	"github.com/cmcoffee/gohort/tools/temptool"
)

// builderAuthoringTools constructs the FULL authoring catalog —
// every workhorse Builder needs to ASSEMBLE artifacts (create_agent,
// update_agent, clone_agent, delete_agent, add_tool, tool_def,
// skill_def, raw call_<credential>, plus the read-only collections
// list). Used for:
//
//   - Builder's OWN chat-orchestrator turn (forOrchestrator=true in
//     resolveWorkerTools). Builder reads worker drafts, validates
//     consistency, then calls tool_def / create_agent itself.
//
//   - Builder invoked as a sub-agent (agent_dispatch / agents(run)),
//     where another agent called Builder for an authoring task. No
//     plan_set escape route there, so Builder authors inline.
//
// Includes raw call_<credential> tools generated by Secure.BuildTools
// — direct authenticated-endpoint access during authoring (Builder
// uses these to probe an API before deciding on the right tool shape).
// Other agents have to use admin-wrapped api-mode temp tools; raw
// access is Builder-exclusive.
func builderAuthoringTools(sess *ToolSession) []AgentToolDef {
	tools := []AgentToolDef{
		ChatToolToAgentToolDefWithSession(&createAgentTool{}, sess),
		ChatToolToAgentToolDefWithSession(&updateAgentTool{}, sess),
		ChatToolToAgentToolDefWithSession(&cloneAgentTool{}, sess),
		ChatToolToAgentToolDefWithSession(&deleteAgentTool{}, sess),
		ChatToolToAgentToolDefWithSession(addToolTool{}, sess),
		ChatToolToAgentToolDefWithSession(temptool.BuildToolDef(), sess),
		ChatToolToAgentToolDefWithSession(skillDefTool(), sess),
		// bridge — wire a registered API credential to a schedule so an
		// agent gets woken when an external service changes. Pure
		// composition over SecureAPI credentials + watch-kind event
		// monitors; Builder references the credential by name (admin owns
		// the secret).
		ChatToolToAgentToolDefWithSession(bridgeDefTool(""), sess),
		// connector — declare a new BRIDGE TYPE (e.g. a calendar via its
		// MCP server) so its whole tool surface becomes available to
		// agents, no code change. LLM authors the config; an admin
		// approves it in Admin > Connectors. Distinct from bridge, which
		// polls one URL; connector registers a capability type.
		ChatToolToAgentToolDefWithSession(connectorDefTool(), sess),
		// collections — read-only enumeration so Builder can
		// resolve user-named collections to IDs when authoring
		// agents (attached_collections=[...]). Mutating
		// collections still happens via the Knowledge surface.
		ChatToolToAgentToolDefWithSession(collectionsListTool(), sess),
		// draft_oauth_credential — Builder scaffolds an OAuth2 credential
		// config from the API's docs; the admin pastes the secret + enables
		// it in the admin UI.
		draftOAuthCredentialToolDef(),
		// draft_api_credential — the non-oauth sibling: plain API key /
		// bearer / header / basic_auth (OPNsense, X-API-Key services, etc.).
		draftAPICredentialToolDef(),
	}
	// Per-credential fetch_url_<name> tools — Builder uses these for
	// authoring-time discovery (probe an endpoint, confirm shape)
	// before wrapping the verified URL into a persistent api-mode
	// temp tool record.
	tools = append(tools, Secure().BuildTools(sess)...)
	return tools
}

// draftOAuthCredentialToolDef lets Builder scaffold an OAuth2 API
// credential ("Builder builds out, admin fills in"). Builder researches
// the API's OAuth flow (grant, token endpoint, scopes, allowed URLs) and
// fills the config; the credential is created DISABLED with no secret, and
// the admin pastes the secret + enables it in Admin > APIs. Builder never
// handles the secret.
func draftOAuthCredentialToolDef() AgentToolDef {
	return AgentToolDef{
		Tool: Tool{
			Name:        "draft_oauth_credential",
			Description: "Scaffold an OAuth2 API credential for the admin to finish. YOU research the API's OAuth (grant type, https token endpoint, scopes, the URL space it covers) from its docs and fill the config in; the credential is created DISABLED and the admin pastes the SECRET in Admin > APIs and enables it. Use when the user wants to wire up an authenticated API (eBay, Google, etc.). You never see or handle the secret. After drafting, tell the user WHICH secret the admin must paste: client_secret (e.g. eBay Cert ID) for client_credentials, the RSA private key for jwt_bearer, the refresh token for refresh_token.",
			Parameters: map[string]ToolParam{
				"name":         {Type: "string", Description: "Short lowercase id (letters/digits/underscores), e.g. \"ebay\". Becomes fetch_url_<name> once live."},
				"grant":        {Type: "string", Enum: []string{"client_credentials", "jwt_bearer", "refresh_token", "password"}, Description: "The grant the API uses: eBay/most vendor APIs = client_credentials; Google service accounts = jwt_bearer; APIs that need a user login (client id+secret AND username+password) = password."},
				"token_url":    {Type: "string", Description: "The https token endpoint, e.g. https://api.ebay.com/identity/v1/oauth2/token."},
				"base_url":     {Type: "string", Description: "The server this credential talks to, host only, e.g. https://api.ebay.com. The admin manages which endpoints under it are allowed, in Admin > APIs."},
				"scope":        {Type: "string", Description: "(optional) Requested scopes, space-separated, e.g. https://api.ebay.com/oauth/api_scope."},
				"client_id":    {Type: "string", Description: "(optional) The non-secret client/app ID, if the user gave it; otherwise the admin adds it."},
				"username":     {Type: "string", Description: "(password grant) the resource-owner username to log in as. The password itself is a secret the admin pastes."},
				"jwt_issuer":   {Type: "string", Description: "(jwt_bearer) the iss claim, e.g. the service-account email."},
				"jwt_subject":  {Type: "string", Description: "(jwt_bearer, optional) the sub claim."},
				"jwt_audience": {Type: "string", Description: "(jwt_bearer, optional) the aud claim; defaults to token_url."},
				"jwt_key_id":   {Type: "string", Description: "(jwt_bearer, optional) the kid header."},
				"description":  {Type: "string", Description: "(optional) What this credential is for."},
			},
			Required: []string{"name", "grant", "token_url", "base_url"},
		},
		Handler: func(args map[string]any) (string, error) {
			c := SecureCredential{
				Name:        strings.TrimSpace(stringArg(args, "name")),
				Type:        SecureCredOAuth2,
				Grant:       strings.TrimSpace(stringArg(args, "grant")),
				TokenURL:    strings.TrimSpace(stringArg(args, "token_url")),
				BaseURL:     strings.TrimSpace(stringArg(args, "base_url")),
				Scope:       strings.TrimSpace(stringArg(args, "scope")),
				ClientID:    strings.TrimSpace(stringArg(args, "client_id")),
				Username:    strings.TrimSpace(stringArg(args, "username")),
				JWTIssuer:   strings.TrimSpace(stringArg(args, "jwt_issuer")),
				JWTSubject:  strings.TrimSpace(stringArg(args, "jwt_subject")),
				JWTAudience: strings.TrimSpace(stringArg(args, "jwt_audience")),
				JWTKeyID:    strings.TrimSpace(stringArg(args, "jwt_key_id")),
				Description: strings.TrimSpace(stringArg(args, "description")),
			}
			if err := Secure().SaveOAuthDraft(c); err != nil {
				return "", err
			}
			secretNeeded := map[string]string{
				OAuthGrantClientCredentials: "the client secret (e.g. eBay Cert ID)",
				OAuthGrantJWTBearer:         "the RSA private key (PEM or JWK)",
				OAuthGrantRefreshToken:      "the refresh token",
				OAuthGrantPassword:          "the client secret AND the user's password (two separate fields)",
			}[c.Grant]
			return fmt.Sprintf("Drafted OAuth2 credential %q (grant=%s), created DISABLED. To finish: in Admin > APIs open %q, paste %s into the secret field, add the client/app ID if it's not set, enable it, then hit Test. It goes live as fetch_url_%s.",
				c.Name, c.Grant, c.Name, secretNeeded, c.Name), nil
		},
	}
}

// credentialFirstGuidance is injected into the system prompt of every
// self-serve authoring agent (any non-Builder agent that gets tool_def + the
// credential-draft tools). It travels with the authoring CAPABILITY rather
// than living hardcoded in one seed prompt, so Chat, custom agents, and any
// future authoring agent all get the same credential-first behavior. Builder
// carries the equivalent in its own persona. No backticks inside (raw string).
const credentialFirstGuidance = `**Wiring an authenticated API is credential-first, and the auth must WORK before you build anything against it.** Do it strictly in this order, do NOT skip ahead:
1. CREATE the gohort credential FIRST. OAuth2 uses draft_oauth_credential; a plain API key, bearer token, custom header, or HTTP basic-auth (e.g. OPNsense) uses draft_api_credential. Set its base_url to the host (e.g. https://192.168.0.1); the admin manages which endpoints under it are allowed.
2. STOP and hand off, then END THE TURN. The credential is created DISABLED. Tell the user exactly which secret the admin pastes in Admin > APIs, to enable it, and for a LAN appliance or any self-signed or IP-addressed host to also turn on "Allow self-signed / skip TLS verification". Do NOT write the tool or agent yet. You cannot author a correct tool against auth that does not exist and that you cannot call.
3. VERIFY before building. When the user says it is set up, FIRST call check_credential(name): if it reports NOT READY (still disabled, or no secret pasted), tell the user exactly what is left, ask them to finish it in Admin > APIs, and STOP — do not probe or build against an unconfigured credential. Only when it reports READY, make ONE probe call through the credential (the auto-generated fetch_url_<name>, or fetch_via in a script) to a simple endpoint. If the probe errors (bad auth, a cert error, or a connection timeout meaning the server cannot reach the host), report the EXACT error and stop. That is a setup problem to fix with the user, not something to code around or retry blindly. Only check_credential READY plus a clean probe means the auth works.
4. THEN build the tool, and only then, now that you can actually probe the API to learn its real endpoints and shapes. Prefer tool_def(mode="api", credential="<name>") over a hand-written shell script; api mode handles the call, the auth, the allow-list, and retries for you.
NEVER take an api key, secret, token, password, or host as a tool PARAMETER, and NEVER ask the user to paste a secret into the chat: the credential injects auth server-side. If you build an AGENT around the API, do not write its prompt to collect login details either. You draft the credential; the admin only pastes the secret in Admin > APIs.`

// draftAPICredentialToolDef is the non-oauth sibling of
// draftOAuthCredentialToolDef: Builder scaffolds a plain key / bearer /
// header / basic_auth credential from the API's docs; the admin pastes the
// secret + enables it. This is how authenticated NON-oauth APIs (OPNsense,
// X-API-Key services, etc.) get wired without ever putting a secret into a
// tool parameter.
func draftAPICredentialToolDef() AgentToolDef {
	return AgentToolDef{
		Tool: Tool{
			Name:        "draft_api_credential",
			Description: "Scaffold a NON-OAuth API credential (plain API key, bearer token, custom header, or HTTP basic-auth) for the admin to finish. Use this for any authenticated API that is NOT OAuth2 — e.g. OPNsense (basic_auth), a service with an X-API-Key header, or a bearer token. YOU research from the docs HOW the API authenticates (which mechanism, which header/param name, the URL space it covers) and fill the config; the credential is created DISABLED and the admin pastes the SECRET in Admin > APIs and enables it. You never see or handle the secret. After drafting, tell the user exactly WHICH value the admin must paste (the API key, the bearer token, or the username:password pair for basic_auth — for OPNsense that's key:secret). Then build the tool with tool_def(mode=\"api\", credential=\"<name>\") — NEVER take the key/secret/host as tool parameters.",
			Parameters: map[string]ToolParam{
				"name":        {Type: "string", Description: "Short lowercase id (letters/digits/underscores), e.g. \"opnsense\". Becomes fetch_url_<name> once live."},
				"type":        {Type: "string", Enum: []string{"bearer", "header", "query", "basic_auth"}, Description: "How the API authenticates: bearer = Authorization: Bearer <token>; header = a custom header (set param_name, e.g. X-API-Key); query = key in a query param (set param_name); basic_auth = HTTP Basic (secret is username:password; OPNsense uses key:secret)."},
				"base_url":    {Type: "string", Description: "The server this credential talks to, host only, no path, e.g. https://192.168.0.1. The admin manages which specific endpoints under it are allowed, in Admin > APIs."},
				"param_name":  {Type: "string", Description: "(header/query only) the header or query-param name, e.g. X-API-Key or apikey."},
				"description": {Type: "string", Description: "(optional) What this credential is for."},
			},
			Required: []string{"name", "type", "base_url"},
		},
		Handler: func(args map[string]any) (string, error) {
			c := SecureCredential{
				Name:        strings.TrimSpace(stringArg(args, "name")),
				Type:        strings.TrimSpace(stringArg(args, "type")),
				BaseURL:     strings.TrimSpace(stringArg(args, "base_url")),
				ParamName:   strings.TrimSpace(stringArg(args, "param_name")),
				Description: strings.TrimSpace(stringArg(args, "description")),
			}
			if err := Secure().SaveAPIDraft(c); err != nil {
				return "", err
			}
			secretNeeded := map[string]string{
				SecureCredBearer:    "the bearer token",
				SecureCredHeader:    "the API key value for the " + c.ParamName + " header",
				SecureCredQuery:     "the API key value for the " + c.ParamName + " query param",
				SecureCredBasicAuth: "the credential as username:password (for OPNsense, key:secret)",
			}[c.Type]
			if secretNeeded == "" {
				secretNeeded = "the secret value"
			}
			return fmt.Sprintf("Drafted %s credential %q, created DISABLED. To finish: in Admin > APIs open %q, paste %s into the secret field, enable it. It goes live as fetch_url_%s. Now build the tool with tool_def(mode=\"api\", credential=%q) — do NOT take the key/secret/host as tool params.",
				c.Type, c.Name, c.Name, secretNeeded, c.Name, c.Name), nil
		},
	}
}

// checkCredentialToolDef is Builder's verify-before-complete check: it reports
// whether a drafted credential is now configured (exists + enabled + secret
// pasted) WITHOUT ever returning the secret. Builder calls it before declaring
// a build done so it can't ship an agent wired to a still-disabled credential —
// instead it tells the user to finish it in Admin > APIs and come back.
func checkCredentialToolDef() AgentToolDef {
	return AgentToolDef{
		Tool: Tool{
			Name:        "check_credential",
			Description: "Verify a credential you DRAFTED is now configured BEFORE you call a build done. Returns whether it exists, is ENABLED, and has its SECRET set — never the secret itself. Call this after telling the user to paste the secret in Admin > APIs. If it is not enabled-with-secret, the build is NOT finished: tell the user exactly what's left, ask them to complete it and come back, and do NOT declare success or wire a tool/agent to it yet.",
			Parameters: map[string]ToolParam{
				"name": {Type: "string", Description: "The credential name you drafted (draft_api_credential / draft_oauth_credential)."},
			},
			Required: []string{"name"},
		},
		Handler: func(args map[string]any) (string, error) {
			name := strings.TrimSpace(stringArg(args, "name"))
			if name == "" {
				return "", fmt.Errorf("name is required")
			}
			exists, enabled, hasSecret := Secure().CredentialStatus(name)
			if !exists {
				return fmt.Sprintf("Credential %q does not exist — draft it first (draft_api_credential / draft_oauth_credential). NOT READY.", name), nil
			}
			if enabled && hasSecret {
				return fmt.Sprintf("Credential %q is READY — enabled and its secret is set. Safe to wire the tool/agent to it and finish.", name), nil
			}
			var missing []string
			if !hasSecret {
				missing = append(missing, "no secret pasted yet")
			}
			if !enabled {
				missing = append(missing, "still disabled")
			}
			return fmt.Sprintf("Credential %q is NOT READY (%s). Tell the user to open Admin > APIs, finish it (paste the secret, enable it), then come back — do NOT declare the build complete or wire anything to it yet.", name, strings.Join(missing, "; ")), nil
		},
	}
}

// builderWorkerResearchTools is the small set of EXTRA tools workers
// get when their parent agent is Builder. The bulk of a worker's
// catalog comes from the standard AllowedTools resolution (web_search,
// fetch_url, browse_page, local, knowledge_search, agents) — those
// cover the research/drafting/testing rhythm. This function adds the
// pieces that aren't globally registered:
//
//   - per-credential fetch_url_<name> — workers may need to probe a
//     registered credential to map out an API's response shape before
//     drafting a wrapper script. Same auth surface Builder uses, but
//     in worker-step context with fresh history per step.
//
// Workers get the FULL authoring catalog alongside the research
// extras. The framework declines to dictate the assembler model — a
// worker step CAN author directly (worker calls tool_def / create_agent
// itself and returns confirmation), or it CAN return components as
// text for Builder to assemble. Both patterns work; the choice is
// left to whichever shape Builder's persona prefers and whichever the
// LLM reaches for naturally. Without this, the model kept trying to
// dispatch back to Builder when its brief asked it to "create" — it
// had the verb but not the tool.
func builderWorkerResearchTools(sess *ToolSession) []AgentToolDef {
	return append(Secure().BuildTools(sess), builderAuthoringTools(sess)...)
}

// isBuilderAgent reports whether the given agent ID corresponds to
// the Builder seed agent. Used by every catalog-assembly path that
// might need to append builderAuthoringTools — orchestrate's
// resolveWorkerTools, dispatch_to_agent's sub-agent build, and
// RunAgentSync's external-dispatch build.
//
// Centralized so future changes to the identity check (e.g.
// allowing user-cloned Builders with a marker on the record) don't
// have to be made in three places.
func isBuilderAgent(agentID string) bool {
	return agentID == "seed-builder"
}

// isCloneOnlySeed reports whether an agent ID is a TEMPLATE seed: one Builder
// clones to produce real, usable agents, but that is never meant to be run or
// published DIRECTLY. Such a seed stays out of the Agency picker and can never
// become publicly exposed — a user gets its capability by cloning it, not by
// selecting the empty template. seed-kb (the Knowledge Base template) is the
// case today: you get a KB by cloning it with your own corpus, not by chatting
// with the corpus-less seed. Centralized like isBuilderAgent so the identity
// check lives in one place.
func isCloneOnlySeed(agentID string) bool {
	return agentID == "seed-kb"
}

// orchestratorRouteKey picks the lead-routing stage for the main reasoning +
// synthesis calls. Builder gets its own stage (default lead, admin-flippable)
// so its agent-design reasoning runs on the stronger model. Every other agent
// stays on the worker-locked orchestrator stage UNLESS it opted into the lead
// model (leadModel), in which case it routes through the non-private
// orchestrator.lead stage (default lead, admin-flippable as a global ceiling).
// All three degrade to worker automatically when no lead model is configured
// (agent_loop's NoLead guard). The leadModel flag is gated for privacy
// upstream — see chatTurn.shouldUseLeadModel.
func orchestratorRouteKey(agentID string, leadModel bool) string {
	if isBuilderAgent(agentID) {
		return "app.orchestrate.builder"
	}
	if leadModel {
		return "app.orchestrate.orchestrator.lead"
	}
	return "app.orchestrate.orchestrator"
}

// builderWorkerDirectives is the cross-cutting authoring discipline
// every Builder-spawned worker should follow. Builder's OrchestratorPrompt
// holds these rules for the conductor turn, but workers don't see
// the orchestrator prompt — only their brief + per-tool fragments.
// Without this block, workers were writing scripts that pip-install
// (won't work in the shipped sandbox), build URLs without encoding
// (breaks on spaces), or use urllib instead of the gohort hook
// (sandbox cuts the network namespace). Injected at runWorkerStep
// in runner.go when the parent agent is Builder.
//
// Kept tight — same rules, no narrative, fits at the end of the
// system prompt without bloating it.
const builderWorkerDirectives = `## Worker discipline — sandbox + script rules

You're a Builder-spawned worker executing one focused step (research / draft / smoke-test). When you write scripts or run shell commands, the following constraints apply:

- **Network goes through gohort.** All HTTP from inside a script flows through ` + "gohort.fetch_url" + ` / ` + "gohort.browse_page" + `, available by default — no ` + "hook_capabilities" + ` declaration needed for the bare set. Canonical: ` + "from gohort import fetch_url; data = fetch_url(url)" + `. ` + "fetch_url" + ` auto-routes JS-heavy hosts through ` + "browse_page" + ` so the same URL that worked for your LLM-tool probe works in the script. **For binary downloads (image, PDF, audio, video, archive)**: pass ` + "save_to=" + ` and the response streams to a workspace file — never try to write ` + "result['body']" + ` to disk for binary data (the string conversion mangles bytes). Example: ` + "r = fetch_url(image_url, save_to='meme.png'); if r['status'] != 200: return f'fetch failed: {r[\"status\"]}'; # file is now at <workspace>/meme.png" + `. **Any network-doing standard library is BLOCKED**: curl, wget, urllib (network parts), requests, http.client, socket — the framework refuses tool_def calls that use them.

- **For credentialed endpoints, declare the credential.** ` + "secret:<name>" + ` returns the decrypted value (script injects it itself); ` + "fetch_via:<name>" + ` routes the request through that credential's secure dispatch (auth applied server-side, URL allow-list enforced, script never sees the secret — prefer this). Example: ` + "hook_capabilities=[\"fetch_via:openweather\"]" + `, then ` + "from gohort import fetch_via; data = fetch_via(\"openweather\", url)" + `. If the credential isn't registered, tell the user to register it via the admin UI; don't invent a credential name.

- **Params arrive as ENV VARS, not sys.argv.** When a tool declares ` + "params={\"count\": ..., \"subreddit\": ...}" + ` and the LLM calls it with ` + "count=3, subreddit=\"memes\"" + `, your script reads them with ` + "os.environ['count']" + ` (Python) / ` + "$count" + ` (bash) / ` + "process.env.count" + ` (node). Do NOT use ` + "sys.argv" + ` / ` + "argparse" + ` — the auto-inferred command_template adds no positional placeholders, so sys.argv[1] doesn't exist and ordering becomes a footgun (alphabetical? insertion?) the framework deliberately sidesteps. Canonical Python: ` + "import os; count = int(os.environ['count']); sub = os.environ['subreddit']" + `. Bash: ` + "count=\"$count\"; sub=\"$subreddit\"" + `. If you absolutely need positional argv (third-party tool that doesn't read env), supply your own command_template with explicit ` + "{placeholder}" + ` args — but you almost never need this.

- **URL encoding is mandatory.** Stitching user values into URLs via f-strings without encoding is the #1 source of "works for Seattle, breaks for Santa Cruz" bugs. Always: ` + "from urllib.parse import quote; url = f\"...?q={quote(city)}\"" + `. The hook refuses URLs with raw whitespace and returns a directive error pointing at this fix — don't make Builder iterate to discover it.

- **When a fetch returns a non-2xx, the FIRST check is the URL itself, not the fetch mechanism.** Look at the hook log line for that call (` + "[hook/fetch] start GET ..." + `). Compare the URL on the wire to the URL you intended to send. Common shapes:
  - ` + "%7Bplaceholder%7D" + ` in the URL = unsubstituted ` + "{placeholder}" + ` — your f-string or .format() never ran. Fix the templating, NOT the fetch.
  - Raw whitespace = unencoded user value (see URL-encoding rule above).
  - Trailing/leading whitespace in path = stray ` + "\\n" + ` from input parsing.
  Do NOT switch from gohort.fetch_url to curl, requests, urllib, or shell commands as a "fresh start" — none of those would behave differently because the bug is in the URL, not the transport. They also CAN'T work — the sandbox runs --unshare-net; the only network path is the gohort hook. The 403/404/400 is the server telling you the URL is bad. Read the URL. Fix the URL. One-line fix beats a rewrite every time.

- **JSON parsing: standard Python, no special method.** ` + "gohort.fetch_url" + ` returns ` + "{status, headers, body}" + `. To parse JSON, check status then ` + "json.loads(body)" + `. Canonical shape:
  ` + "result = fetch_url(url)" + `
  ` + "if result['status'] != 200: return f\"upstream {result['status']}: {result['body'][:200]}\"" + `
  ` + "data = json.loads(result['body'])" + `
  There is no separate fetch_json tool — script-side OR LLM-callable. ` + "fetch_url" + ` returns the body as a string in every case; if you need parsed data, ` + "json.loads()" + ` it. Probing an API endpoint inline (LLM-level)? Same shape — read the JSON text in the tool result and reason about it.

- **403 from anti-bot ⇒ ` + "gohort.browse_page" + `**. ` + "fetch_url" + ` already auto-routes JS-heavy hosts (Reddit, Twitter/X, etc.) through Chromium for you, but if a non-listed host returns 403 / captcha / Cloudflare interstitial / a JS-skeleton, fall through manually: ` + "if result['status'] == 403: result = browse_page(url)" + `. browse_page runs real headless Chromium server-side — executes JS, handles cookies, beats most soft blocks. 5-20s per call so it's the recovery path, not the default.

- **Stdlib only in scripts.** No requests, no Pillow, no numpy/pandas, no bs4. Stdlib: json, urllib.parse (for encoding, not for fetching), re, datetime, math, statistics, base64, hashlib, html, sys, os, argparse. If the design needs a third-party lib, pivot conceptually (different approach via stdlib + hook).

- **Your catalog includes authoring tools (tool_def, create_agent, add_tool, skill_def) alongside research tools.** Use whichever fits the step's brief — if the step is "create the X tool with this spec," call tool_def yourself and return confirmation + the saved record. If the step is "research / draft / probe," return findings as text for Builder to assemble. Don't dispatch ` + "agents(action=\"run\", agent=\"Builder\")" + ` to ask Builder to do something — you have the same tools Builder does. If you authored an artifact, INCLUDE the artifact's name/id in your report so Builder can mention it in the final user-facing summary.

- **Documented APIs only, with hard search caps.** When asked to probe a specific named provider:
  - **2 web_searches max** to find the provider's documentation URL (try "<provider> API documentation", "<provider> OpenAPI spec"). If two searches don't surface OFFICIAL documentation (the provider's own docs site, not forum posts, not third-party blogs, not GitHub mirrors of unofficial reverse-engineering), STOP and report back "no public documentation found for <provider>." Don't search a third time hoping to find it — if it's not in the first two searches, it's not public.
  - **2 fetch_url calls max** on the documentation site itself once located (a docs index + the specific endpoint reference page is enough for shape). Don't read the entire docs site.
  - **NEVER probe endpoints directly to map shapes.** Hitting the actual API surface with fetch_url to "see what comes back" is the failure mode — it produces fragile tools and burns rounds. The docs are the source of truth.
- **Auth errors are a STOP signal, not a "try harder" signal.** If a probe returns HTTP 401 / 403 / 407, OR if fetch_url returns an upstream error explicitly demanding auth (the response body says "invalid api key", "authentication required", "401 Unauthorized"), STOP. Don't try the same endpoint twice. Don't try a "different auth shape." Report back: "endpoint <URL> requires <provider> API credentials; the user needs to supply an API key before this tool can be built." 4 consecutive unauthenticated failures is not exploration — it's wasted rounds.

- **Be compact in your report-back.** You return COMPONENTS to Builder for assembly. Builder's context is finite. If you're returning a drafted script_body, return JUST the script content — no commentary above/below unless it's truly necessary for assembly. If you're returning an API shape from a PROBE step, return the structured summary (endpoint + fields + sample response), not the raw blob.

- **Named unit conversions.** If your script does any unit math, each conversion is its own function naming BOTH units (c_to_f, mph_to_kmh, kmh_to_mph, m_to_ft). Never cross-applied. When the upstream API supports unit query params (temperature_unit, wind_speed_unit), use them and skip the conversion.

- **Don't fetch fields you don't use.** Every field requested from an API should appear in the output (or feed an intermediate calc that does). Unused fetched data is dead bandwidth + dead context.

- **No quote-wrapping placeholders.** When writing command_template or url_template (if you're drafting these for Builder), {placeholders} are auto-quoted/encoded by the framework. NEVER wrap them in your own quote characters.

- **Capture mistakes and gotchas via store_fact.** When you make a mistake the framework or test_args catches (forgot URL encoding, wrote a wrapper around gohort.fetch without importing it, tried urllib in the sandbox, used a library not present) — store_fact with the FAILURE PATH as a rule. When you discover an API quirk worth knowing (200 + empty body on missing key, User-Agent required, weird pagination shape) — store_fact that too. Same namespace as Builder, so the lesson surfaces in Builder's next session. NO permission needed for operational knowledge.

  Frame as a RULE not a story: "When using gohort.fetch, import gohort first or get NameError" (rule) — not "I wrote def fetch and forgot import" (story). Skip when the finding is specific to one tool (a particular endpoint URL, a credential name) — that's a detail, not a lesson, and it bloats Builder's prompt without value.`
