// Builder's exclusive tool catalog. These tools are NOT globally
// registered — they have no entries in RegisteredChatTools(), can't
// be resolved by FindChatTool, and are invisible to every enumerator
// in the codebase. The Builder seed agent gets them by way of this
// constructor: when the runner assembles the catalog for an agent
// whose ID is "seed-builder", it appends the result of
// builderInternalTools() to the static tool list.
//
// Any other agent — Chat, Research, Phantom-dispatched agents, even
// a user-cloned Builder copy with a different ID — has no path to
// these tools. There's nothing to "filter out" because the tools
// were never in the pool to begin with.

package orchestrate

import (
	. "github.com/cmcoffee/gohort/core"
	"github.com/cmcoffee/gohort/tools/temptool"
)

// builderInternalTools constructs the authoring tool catalog bound
// to sess. Called exactly once per Builder turn (in resolveWorkerTools
// + each dispatch path), so each session gets a fresh tool_def
// instance with no cross-session state.
//
// Includes the raw `call_<credential>` secure-API tools generated by
// SecureAPI.BuildTools — Builder is the ONLY agent that gets direct
// auth-API access. Every other agent has to use wrapped api-mode
// temp tools the admin has approved (or dispatch_to_agent to an
// agent that has them). Direct call_<cred> gives the LLM
// considerable latitude (any matching URL, any method, any body);
// constraining it to Builder keeps that surface scoped to the agent
// that needs it for endpoint discovery during authoring.
func builderInternalTools(sess *ToolSession) []AgentToolDef {
	tools := []AgentToolDef{
		ChatToolToAgentToolDefWithSession(&createAgentTool{}, sess),
		ChatToolToAgentToolDefWithSession(&updateAgentTool{}, sess),
		ChatToolToAgentToolDefWithSession(&cloneAgentTool{}, sess),
		ChatToolToAgentToolDefWithSession(&deleteAgentTool{}, sess),
		ChatToolToAgentToolDefWithSession(addToolTool{}, sess),
		ChatToolToAgentToolDefWithSession(temptool.BuildToolDef(), sess),
		ChatToolToAgentToolDefWithSession(skillDefTool(), sess),
		// collections — read-only enumeration so Builder can
		// resolve user-named collections to IDs when authoring
		// agents (attached_collections=[...]). Mutating
		// collections still happens via the Knowledge surface.
		ChatToolToAgentToolDefWithSession(collectionsListTool(), sess),
	}
	// Raw secure-API call_<credential> tools — exclusive to Builder.
	// Allows authoring-time discovery against the deployment's
	// registered credentials before wrapping the working URL into a
	// persistent api-mode temp tool.
	tools = append(tools, Secure().BuildTools(sess)...)
	return tools
}

// isBuilderAgent reports whether the given agent ID corresponds to
// the Builder seed agent. Used by every catalog-assembly path that
// might need to append builderInternalTools — orchestrate's
// resolveWorkerTools, dispatch_to_agent's sub-agent build, and
// RunAgentSync's external-dispatch build.
//
// Centralized so future changes to the identity check (e.g.
// allowing user-cloned Builders with a marker on the record) don't
// have to be made in three places.
func isBuilderAgent(agentID string) bool {
	return agentID == "seed-builder"
}
