package core

import (
	"strings"
	"testing"

	"github.com/cmcoffee/snugforge/kvlite"
)

// A user-owned credential could not be secured at all: SetSecured reads the
// GLOBAL key and a user's credential lives at credStoreKey(owner, name). So
// every credential someone managed themselves was Open, and an Open credential
// gets an auto-generated fetch_url_<name> — a person's own API key reachable by
// every agent they had.

func securedStore(t *testing.T) *SecureAPI {
	t.Helper()
	return &SecureAPI{db: &DBase{Store: kvlite.MemStore()}}
}

// TestSecuringAUserOwnedCredential — the gap itself.
func TestSecuringAUserOwnedCredential(t *testing.T) {
	s := securedStore(t)
	if err := s.Save(SecureCredential{Name: "mykey", Type: SecureCredBearer,
		BaseURL: "https://api.example.com", Owner: "craig"}, "sk-1"); err != nil {
		t.Fatalf("save: %v", err)
	}
	if c, _ := s.LoadUser("craig", "mykey"); c.Secured {
		t.Fatal("a new credential is secured by default — every existing record would change meaning")
	}
	if err := s.SetSecuredOwned("craig", "mykey", true); err != nil {
		t.Fatalf("secure: %v", err)
	}
	c, ok := s.LoadUser("craig", "mykey")
	if !ok || !c.Secured {
		t.Fatal("the user-owned credential was not secured")
	}
	// And back off again — a one-way door would be its own bug.
	if err := s.SetSecuredOwned("craig", "mykey", false); err != nil {
		t.Fatalf("unsecure: %v", err)
	}
	if c, _ := s.LoadUser("craig", "mykey"); c.Secured {
		t.Error("securing could not be undone")
	}
}

// TestSecuringNeverCrossesNamespaces — the reason a separate setter exists. A
// global credential of the same name must not be touched by a user securing
// theirs, and vice versa.
func TestSecuringNeverCrossesNamespaces(t *testing.T) {
	s := securedStore(t)
	s.Save(SecureCredential{Name: "shared", Type: SecureCredBearer, BaseURL: "https://x.example"}, "g")
	s.Save(SecureCredential{Name: "shared", Type: SecureCredBearer, BaseURL: "https://x.example", Owner: "craig"}, "u")

	if err := s.SetSecuredOwned("craig", "shared", true); err != nil {
		t.Fatalf("secure owned: %v", err)
	}
	if g, _ := s.Load("shared"); g.Secured {
		t.Error("securing a user's credential secured the GLOBAL one of the same name")
	}
	if u, _ := s.LoadUser("craig", "shared"); !u.Secured {
		t.Error("the user's own credential was not secured")
	}
	// Another user's namespace is untouched and unreachable.
	if err := s.SetSecuredOwned("bob", "shared", true); err == nil {
		t.Error("securing succeeded for a user who owns no such credential")
	}
}

// TestSavePreservesSecured — Save deliberately keeps the flag from the stored
// record, so editing a credential without mentioning it cannot silently reopen
// one that was locked down.
func TestSavePreservesSecured(t *testing.T) {
	s := securedStore(t)
	s.Save(SecureCredential{Name: "k", Type: SecureCredBearer, BaseURL: "https://a.example", Owner: "craig"}, "s")
	s.SetSecuredOwned("craig", "k", true)

	// An ordinary edit — a new description, no Secured field set at all.
	if err := s.Save(SecureCredential{Name: "k", Type: SecureCredBearer,
		BaseURL: "https://a.example", Description: "edited", Owner: "craig"}, ""); err != nil {
		t.Fatalf("edit: %v", err)
	}
	c, _ := s.LoadUser("craig", "k")
	if !c.Secured {
		t.Error("an edit reopened a secured credential to every agent")
	}
	if c.Description != "edited" {
		t.Errorf("the edit did not land: %q", c.Description)
	}
}

// TestABlankOwnerFallsThroughToGlobal — so callers need no branch.
func TestABlankOwnerFallsThroughToGlobal(t *testing.T) {
	s := securedStore(t)
	s.Save(SecureCredential{Name: "g", Type: SecureCredBearer, BaseURL: "https://a.example"}, "s")
	if err := s.SetSecuredOwned("", "g", true); err != nil {
		t.Fatalf("global via owned setter: %v", err)
	}
	if c, _ := s.Load("g"); !c.Secured {
		t.Error("a blank owner did not reach the global credential")
	}
	if err := s.SetSecuredOwned("craig", "nope", true); err == nil ||
		!strings.Contains(err.Error(), "not found") {
		t.Errorf("securing a missing credential should say so: %v", err)
	}
}

// TestSecuringRemovesTheAutoGeneratedTool — the behaviour the toggle exists for,
// asserted through the catalog rather than the flag.
//
// A stored bool is not the promise. The promise is that no agent gets a
// fetch_url_<name> for this credential any more, and that is decided in
// BuildTools — so this drives BuildTools and would catch the flag being set
// correctly while the catalog kept emitting the tool anyway.
func TestSecuringRemovesTheAutoGeneratedTool(t *testing.T) {
	s := securedStore(t)
	if err := s.Save(SecureCredential{Name: "mykey", Type: SecureCredBearer,
		BaseURL: "https://api.example.com", Owner: "craig"}, "sk-1"); err != nil {
		t.Fatalf("save: %v", err)
	}
	sess := &ToolSession{Username: "craig"}

	if !catalogHasTool(s, sess, "fetch_url_mykey") {
		t.Fatal("an OPEN user credential produced no tool — the baseline this test compares against is wrong")
	}
	if err := s.SetSecuredOwned("craig", "mykey", true); err != nil {
		t.Fatalf("secure: %v", err)
	}
	if catalogHasTool(s, sess, "fetch_url_mykey") {
		t.Error("the credential is secured but every agent still gets its tool — " +
			"the toggle changed a flag and nothing else")
	}
	// Reopening restores it, so the control is not a one-way door.
	s.SetSecuredOwned("craig", "mykey", false)
	if !catalogHasTool(s, sess, "fetch_url_mykey") {
		t.Error("reopening the credential did not restore its tool")
	}
}

// TestSecuringOneCredentialLeavesTheOthers — a lock is only useful if it is
// narrow. Securing one must not quietly remove the rest from the catalog.
func TestSecuringOneCredentialLeavesTheOthers(t *testing.T) {
	s := securedStore(t)
	s.Save(SecureCredential{Name: "locked", Type: SecureCredBearer, BaseURL: "https://a.example", Owner: "craig"}, "1")
	s.Save(SecureCredential{Name: "open", Type: SecureCredBearer, BaseURL: "https://b.example", Owner: "craig"}, "2")
	s.SetSecuredOwned("craig", "locked", true)

	sess := &ToolSession{Username: "craig"}
	if catalogHasTool(s, sess, "fetch_url_locked") {
		t.Error("the secured credential still has a tool")
	}
	if !catalogHasTool(s, sess, "fetch_url_open") {
		t.Error("securing one credential removed another user credential's tool")
	}
}

func catalogHasTool(s *SecureAPI, sess *ToolSession, name string) bool {
	for _, td := range s.BuildTools(sess) {
		if td.Tool.Name == name {
			return true
		}
	}
	return false
}
