// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReadRoot(arg1) {
  return window['go']['main']['App']['AddReadRoot'](arg1);
}

export function ApproveInvoke(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApproveInvoke'](arg1, arg2, arg3);
}

export function GetAllowedTools() {
  return window['go']['main']['App']['GetAllowedTools']();
}

export function GetAutoApprove() {
  return window['go']['main']['App']['GetAutoApprove']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetReadRoots() {
  return window['go']['main']['App']['GetReadRoots']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InstallBridge() {
  return window['go']['main']['App']['InstallBridge']();
}

export function InvokeTool(arg1, arg2) {
  return window['go']['main']['App']['InvokeTool'](arg1, arg2);
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function LogOut() {
  return window['go']['main']['App']['LogOut']();
}

export function PickReadRoot() {
  return window['go']['main']['App']['PickReadRoot']();
}

export function RemoveAllowedTool(arg1) {
  return window['go']['main']['App']['RemoveAllowedTool'](arg1);
}

export function RemoveReadRoot(arg1) {
  return window['go']['main']['App']['RemoveReadRoot'](arg1);
}

export function RequestApprovalBlocking(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestApprovalBlocking'](arg1, arg2, arg3);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SetAutoApprove(arg1) {
  return window['go']['main']['App']['SetAutoApprove'](arg1);
}

export function SetBridgeAPIKey(arg1) {
  return window['go']['main']['App']['SetBridgeAPIKey'](arg1);
}

export function UninstallBridge() {
  return window['go']['main']['App']['UninstallBridge']();
}
