// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddReadRoot(arg1:string):Promise<main.save_result>;

export function ApproveInvoke(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function GetAllowedTools():Promise<Array<string>>;

export function GetAutoApprove():Promise<boolean>;

export function GetLogs():Promise<Array<main.LogLine>>;

export function GetReadRoots():Promise<Array<string>>;

export function GetSettings():Promise<main.settings_view>;

export function InstallBridge():Promise<main.save_result>;

export function InvokeTool(arg1:string,arg2:{[key: string]: any}):Promise<string>;

export function IsConfigured():Promise<boolean>;

export function ListTools():Promise<Array<main.tool_descriptor>>;

export function LogOut():Promise<main.save_result>;

export function PickReadRoot():Promise<main.pick_result>;

export function RemoveAllowedTool(arg1:string):Promise<main.save_result>;

export function RemoveReadRoot(arg1:string):Promise<main.save_result>;

export function RequestApprovalBlocking(arg1:string,arg2:string,arg3:{[key: string]: any}):Promise<boolean>;

export function ResetSettings():Promise<main.save_result>;

export function SaveSettings(arg1:string,arg2:string):Promise<main.save_result>;

export function SetAutoApprove(arg1:boolean):Promise<main.save_result>;

export function SetBridgeAPIKey(arg1:string):Promise<main.save_result>;

export function UninstallBridge():Promise<main.save_result>;
